/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * @format
 */

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  sidebar: [
    "index",
    {
      type: "category",
      label: "Observability",
      items: [
        {
          type: "category",
          label: "Tutorials",
          collapsible: false,
          items: [
            {
              type: "autogenerated",
              dirName: "observability/tutorials",
              className: "hidden",
            },
          ],
          link: { type: "doc", id: "observability/tutorials/index" },
        },
        {
          type: "category",
          label: "How-to Guides",
          collapsible: false,
          items: [
            {
              type: "autogenerated",
              dirName: "observability/how_to_guides",
              className: "hidden",
            },
          ],
          link: { type: "doc", id: "observability/how_to_guides/index" },
        },
        {
          type: "category",
          label: "Conceptual Guide",
          collapsible: false,
          items: [
            {
              type: "autogenerated",
              dirName: "observability/concepts",
              className: "hidden",
            },
          ],
          link: { type: "doc", id: "observability/concepts/index" },
        },
      ],
      link: { type: "doc", id: "observability/tutorials/index" },
    },
    {
      type: "category",
      label: "Evaluation",
      items: [
        "evaluation/index",
        {
          type: "category",
          label: "Tutorials",
          collapsible: false,
          items: [
            {
              type: "autogenerated",
              dirName: "evaluation/tutorials",
              className: "hidden",
            },
          ],
          link: { type: "doc", id: "evaluation/tutorials/index" },
        },
        {
          type: "category",
          label: "How-to Guides",
          collapsible: false,
          items: [
            {
              type: "autogenerated",
              dirName: "evaluation/how_to_guides",
              className: "hidden",
            },
          ],
          link: { type: "doc", id: "evaluation/how_to_guides/index" },
        },
        {
          type: "category",
          label: "Conceptual Guide",
          collapsible: false,
          items: [
            {
              type: "autogenerated",
              dirName: "evaluation/concepts",
              className: "hidden",
            },
          ],
          link: { type: "doc", id: "evaluation/concepts/index" },
        },
      ],
      link: { type: "doc", id: "evaluation/index" },
    },
    {
      type: "category",
      label: "Prompt Engineering",
      items: [
        {
          type: "category",
          label: "Tutorials",
          collapsible: false,
          items: [
            {
              type: "autogenerated",
              dirName: "prompt_engineering/tutorials",
              className: "hidden",
            },
          ],
          link: { type: "doc", id: "prompt_engineering/tutorials/index" },
        },
        {
          type: "category",
          label: "How-to Guides",
          collapsible: false,
          items: [
            {
              type: "autogenerated",
              dirName: "prompt_engineering/how_to_guides",
              className: "hidden",
            },
          ],
          link: { type: "doc", id: "prompt_engineering/how_to_guides/index" },
        },
        {
          type: "category",
          label: "Conceptual Guide",
          collapsible: false,
          items: [
            {
              type: "autogenerated",
              dirName: "prompt_engineering/concepts",
              className: "hidden",
            },
          ],
          link: { type: "doc", id: "prompt_engineering/concepts/index" },
        },
      ],
      link: { type: "doc", id: "prompt_engineering/tutorials/index" },
    },
    "langgraph_cloud",
    {
      type: "html",
      value:
        '<hr class="dropdown-separator" style="margin-top: 0.5rem; margin-bottom: 0.5rem">',
    },
    {
      type: "category",
      label: "Administration",
      items: [
        {
          type: "category",
          label: "Tutorials",
          collapsible: false,
          items: [
            {
              type: "autogenerated",
              dirName: "administration/tutorials",
              className: "hidden",
            },
          ],
          link: { type: "doc", id: "administration/tutorials/index" },
        },
        {
          type: "category",
          label: "How-to Guides",
          collapsible: false,
          items: [
            {
              type: "autogenerated",
              dirName: "administration/how_to_guides",
              className: "hidden",
            },
          ],
          link: { type: "doc", id: "administration/how_to_guides/index" },
        },
        {
          type: "category",
          label: "Conceptual Guide",
          collapsible: false,
          items: [
            {
              type: "autogenerated",
              dirName: "administration/concepts",
              className: "hidden",
            },
          ],
          link: { type: "doc", id: "administration/concepts/index" },
        },
      ],
      link: { type: "doc", id: "administration/tutorials/index" },
    },
    {
      type: "category",
      label: "Self-hosting",
      collapsed: true,
      collapsible: true,
      items: [
        {
          type: "autogenerated",
          dirName: "self_hosting",
        },
      ],
      link: { type: "doc", id: "self_hosting/index" },
    },
    "administration/pricing",
    {
      type: "html",
      value:
        '<hr class="dropdown-separator" style="margin-top: 0.5rem; margin-bottom: 0.5rem">',
    },
    {
      type: "category",
      label: "Reference",
      collapsed: false,
      collapsible: false,
      items: [
        {
          type: "autogenerated",
          dirName: "reference",
          className: "hidden",
        },
      ],
      link: { type: "doc", id: "reference/index" },
    },
  ],
};
