/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * @format
 */

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  sidebar: [
    "index",
    {
      type: "category",
      label: "Tutorials",
      items: [
        {
          type: "autogenerated",
          dirName: "tutorials",
        },
      ],
      link: { type: "doc", id: "tutorials/index" },
    },
    {
      type: "category",
      label: "How-to guides",
      items: [
        {
          type: "autogenerated",
          dirName: "how_to_guides",
        },
      ],
      link: { type: "doc", id: "how_to_guides/index" },
    },
    {
      type: "category",
      label: "Concepts",
      items: [
        {
          type: "autogenerated",
          dirName: "concepts",
        },
      ],
      link: { type: "doc", id: "concepts/index" },
    },
    {
      type: "category",
      label: "Observability",
      items: [
        {
          type: "autogenerated",
          dirName: "observability",
        },
      ],
      link: { type: "doc", id: "observability/concepts/index" },
    },
    {
      type: "category",
      label: "Evaluation",
      items: [
        {
          type: "autogenerated",
          dirName: "evaluation",
        },
      ],
      link: { type: "doc", id: "evaluation/concepts/index" },
    },
    {
      type: "category",
      label: "Prompt Engineering",
      items: [
        {
          type: "autogenerated",
          dirName: "prompt_engineering",
        },
      ],
      link: { type: "doc", id: "prompt_engineering/concepts/index" },
    },
    {
      type: "category",
      label: "Reference",
      items: [
        {
          type: "autogenerated",
          dirName: "reference",
        },
      ],
      link: { type: "doc", id: "reference/index" },
    },
    "pricing",
    {
      type: "category",
      label: "Self-hosting",
      collapsed: true,
      collapsible: true,
      items: [
        {
          type: "autogenerated",
          dirName: "self_hosting",
        },
      ],
      link: { type: "doc", id: "self_hosting/index" },
    },
    "langgraph_cloud",
  ],
};
