/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * @format
 */

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  sidebar: [
    "index",
    "overview",
    {
      type: "category",
      label: "Tracing",
      collapsed: false,
      collapsible: false,
      items: [{ type: "autogenerated", dirName: "tracing" }],
      link: {
        type: "generated-index",
      },
    },
    {
      type: "category",
      label: "Testing & Evaluation",
      collapsed: false,
      collapsible: false,
      items: [{ type: "autogenerated", dirName: "evaluation" }],
      link: {
        type: "generated-index",
      },
    },
    {
      type: "category",
      label: "Organizations",
      collapsed: false,
      collapsible: false,
      items: [
        { type: "autogenerated", dirName: "organizations" }
      ],
      link: {
        type: "generated-index",
        description: 'Use LangSmith to collaborate with your team on all your LLM applications. Check out the guides below for more information.',
      },
    },
    {
      type: "category",
      label: "Hub",
      collapsed: false,
      collapsible: false,
      items: [
        { type: "autogenerated", dirName: "hub" }
      ],
      link: {
        type: "generated-index",
        description: 'Discover, share, and version control prompts in the LangChain Hub.',
      },
    }
  ],
};
