name: Update Submodule on Webhook

on:
  workflow_dispatch:
  repository_dispatch:

jobs:
  update-submodule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout langsmith-docs
        uses: actions/checkout@v2
        with:
          repository: langchain-ai/langsmith-docs
          token: ${{ secrets.GITHUB_TOKEN }}
          path: langsmith-docs
      
      - name: Update submodule
        run: |
          cd langsmith-docs
          git submodule update --init --recursive
          git submodule update --remote subdirectories/langsmith-cookbook
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add subdirectories/langsmith-cookbook
          git diff --staged --quiet || git commit -m "Update langsmith-cookbook submodule to latest commit"
          git push origin HEAD:refs/heads/update-submodule-${{ github.sha }}
